# Generated by Django 3.0.8 on 2020-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20201102_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('Friday', models.ManyToManyField(related_name='_mealplan_Friday_+', to='plans.Meal')),
                ('Monday', models.ManyToManyField(related_name='_mealplan_Monday_+', to='plans.Meal')),
                ('Saturday', models.ManyToManyField(related_name='_mealplan_Saturday_+', to='plans.Meal')),
                ('Sunday', models.ManyToManyField(related_name='_mealplan_Sunday_+', to='plans.Meal')),
                ('Thursday', models.ManyToManyField(related_name='_mealplan_Thursday_+', to='plans.Meal')),
                ('Tuesday', models.ManyToManyField(related_name='_mealplan_Tuesday_+', to='plans.Meal')),
                ('wednesday', models.ManyToManyField(related_name='_mealplan_wednesday_+', to='plans.Meal')),
            ],
        ),
    ]
