# Generated by Django 3.0.8 on 2020-11-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='length',
            field=models.CharField(default='7 Days', max_length=100),
        ),
    ]
