# Generated by Django 3.0.8 on 2020-11-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_mealplan_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
