# Generated by Django 3.0.8 on 2020-11-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_meal_meal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='description',
            field=models.CharField(default='description pending', max_length=300),
        ),
    ]
