# Generated by Django 3.0.8 on 2020-11-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_mealplan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Difficulty', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.PlanLevel'),
        ),
    ]
