# Generated by Django 3.0.8 on 2020-11-30 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20201130_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.PlanLevel'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
