# Generated by Django 3.0.8 on 2020-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20201130_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='vegetarian_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
