# Generated by Django 3.0.8 on 2020-11-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_mealplan_vegetarian_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_thumb_nail',
            field=models.ImageField(default='default-profile-img.png', upload_to='mealPlanThumbNails'),
        ),
    ]
