# Generated by Django 3.0.8 on 2020-11-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_auto_20201130_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ame', models.CharField(max_length=254)),
                ('plan_thumb_nail', models.ImageField(default='Meal Plan Premium.jpg', upload_to='WorkOutThumbNails')),
                ('length', models.CharField(default='7 Days', max_length=100)),
                ('description', models.CharField(default='description pending', max_length=300)),
                ('is_premium', models.BooleanField(default=True)),
                ('Friday2', models.ManyToManyField(related_name='_workoutplan_Friday2_+', to='plans.Workout')),
                ('Monday2', models.ManyToManyField(related_name='_workoutplan_Monday2_+', to='plans.Workout')),
                ('Saturday2', models.ManyToManyField(related_name='_workoutplan_Saturday2_+', to='plans.Workout')),
                ('Sunday2', models.ManyToManyField(related_name='_workoutplan_Sunday2_+', to='plans.Workout')),
                ('Thursday2', models.ManyToManyField(related_name='_workoutplan_Thursday2_+', to='plans.Workout')),
                ('Tuesday2', models.ManyToManyField(related_name='_workoutplan_Tuesday2_+', to='plans.Workout')),
                ('difficulty_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.PlanLevel')),
                ('wednesday2', models.ManyToManyField(related_name='_workoutplan_wednesday2_+', to='plans.Workout')),
            ],
        ),
    ]
