# Generated by Django 3.0.8 on 2020-11-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_profile_subscription_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default-profile-img.png', upload_to='profile_pics'),
        ),
    ]
